namespace AIContentFactory.Api.Models.Entities;

/// <summary>
/// A ranked content opportunity generated by Agent 3 (Viral Analyzer).
/// This is a strategic content blueprint - NOT a final script.
/// </summary>
public sealed class ContentOpportunity
{
    public long Id { get; set; }

    /// <summary>FK to viral_analysis_runs.id.</summary>
    public long AnalysisRunId { get; set; }

    /// <summary>1 = TOP 1 recommendation; higher values are lower-ranked alternates.</summary>
    public int Rank { get; set; }

    public string Topic { get; set; } = string.Empty;
    public string Angle { get; set; } = string.Empty;
    public string? TargetAudience { get; set; }
    public string Hook { get; set; } = string.Empty;
    public string Format { get; set; } = string.Empty;

    /// <summary>Content structure flow, e.g. ["Hook", "Problem", "Solution"].</summary>
    public string[]? Structure { get; set; }

    public string? Emotion { get; set; }
    public string? PsychologicalTrigger { get; set; }
    public string WhyNow { get; set; } = string.Empty;
    public string? ContentGap { get; set; }
    public string? DifferentiationStrategy { get; set; }

    /// <summary>Recommended call-to-action for the content opportunity.</summary>
    public string? CallToAction { get; set; }

    /// <summary>0-100. How attractive this opportunity is.</summary>
    public decimal OpportunityScore { get; set; }

    /// <summary>0-100. How strong the evidence is supporting this opportunity.</summary>
    public decimal ConfidenceScore { get; set; }

    /// <summary>Low / Medium / High.</summary>
    public string RiskLevel { get; set; } = "Medium";

    /// <summary>IDs of trending_videos supporting this opportunity.</summary>
    public long[]? SupportingVideoIds { get; set; }

    public string Evidence { get; set; } = string.Empty;
    public DateTimeOffset CreatedAt { get; set; }
}